apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: dataplatform
  labels:
    component: hive-metastore
spec:
  selector:
    matchLabels:
      component: hive-metastore
  replicas: 1
  template:
    metadata:
      labels:
        component: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: jasoncarneiro/open-dataplatform-hive:latest
          ports:
            - containerPort: 9083
              name: thift
          env:
            - name: NODE_TYPE
              value: metastore
          args:
            - "bash"
            - "-c"
            - "hive --service metastore & tail -F /tmp/root/hive.log"
          volumeMounts:
            - name: hive-site
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
            - name: core-site
              mountPath: /etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: hdfs-site
              mountPath: /etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
      volumes:
        - name: core-site
          configMap:
            name: core-site-datanode
        - name: hive-site
          configMap:
            name: hive-site
        - name: hdfs-site
          configMap:
            name: hdfs-site-datanode
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore-svc
  namespace: dataplatform
spec:
  selector:
    component: hive-metastore
  type: ClusterIP
  ports:
    - name: thrift
      protocol: TCP
      port: 9083
