apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-server
  namespace: dataplatform
  labels:
    component: hive-server
spec:
  selector:
    matchLabels:
      component: hive-server
  replicas: 1
  template:
    metadata:
      labels:
        component: hive-server
    spec:
      containers:
        - name: hive-server
          image: jasoncarneiro/open-dataplatform-hive:latest
          ports:
            - containerPort: 10002
              name: hive
          args:
            - "bash"
            - "-c"
            - "hiveserver2 & tail -F /tmp/root/hive.log"
          volumeMounts:
            - name: hive-site
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
            - name: core-site
              mountPath: /etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: hdfs-site
              mountPath: /etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
      volumes:
        - name: core-site
          configMap:
            name: core-site-datanode
        - name: hdfs-site
          configMap:
            name: hdfs-site-datanode
        - name: hive-site
          configMap:
            name: hive-site
