kind: ConfigMap
apiVersion: v1
metadata:
  name: airflow-pod-template
  namespace: airflow
data:
  pod-template.yml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: airflow-pod
      namespace: airflow
    spec:
      serviceAccountName: airflow
      initContainers:
        - name: sync
          image: k8s.gcr.io/git-sync/git-sync:v3.3.4
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          env:
            - name: GIT_SYNC_ROOT
              value: /git
            - name: GIT_SYNC_DEST
              value: repo
            - name: GIT_SYNC_REPO
              value: https://github.com/jasondavindev/open-dataplatform.git
            - name: GIT_SYNC_BRANCH
              value: fix/airflow-dags
            - name: GIT_SYNC_REV
              value: HEAD
            - name: GIT_SYNC_DEPTH
              value: "0"
            - name: GIT_SYNC_WAIT
              value: "60"
            - name: GIT_SYNC_TIMEOUT
              value: "120"
            - name: GIT_SYNC_ADD_USER
              value: "true"
            - name: GIT_SYNC_MAX_FAILURES
              value: "0"
            - name: GIT_KNOWN_HOSTS
              value: "false"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
          volumeMounts:
            - name: dags
              mountPath: /git
      containers:
        - name: airflow-task-runner
          image: open-dataplatform-airflow:v1.0
          args: []
          command: []
          env:
            - name: POSTGRES_HOST
              value: airflow-postgres-svc.airflow.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: EXECUTOR
              value: KubernetesExecutor
            - name: HDFS_HOST
              value: hdfs://namenode-svc.dataplatform.svc.cluster.local:8020
            - name: PYTHONUNBUFFERED
              value: '1'
          volumeMounts:
            - name: config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg
            - name: dags
              mountPath: /opt/airflow/dags
            - name: airflow-logs
              mountPath: "/opt/airflow/logs"
      restartPolicy: Never
      nodeSelector: {}
      affinity: {}
      tolerations: []
      volumes:
        - name: config
          configMap:
            name: airflow-config
        - name: dags
          emptyDir: {}
        - name: airflow-logs
          emptyDir: {}
