apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: airflow
  labels:
    app: scheduler
spec:
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      serviceAccountName: airflow
      containers:
        - name: scheduler
          image: open-dataplatform-airflow:v1.0
          env:
            - name: POSTGRES_HOST
              value: airflow-postgres-svc.airflow.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: EXECUTOR
              value: KubernetesExecutor
            - name: HDFS_HOST
              value: hdfs://namenode-svc.dataplatform.svc.cluster.local:8020
            - name: INGESTION_API_URL
              value: http://ingestion-api-svc.dataplatform.svc.cluster.local:3000
            - name: SCRIPTS_PATH_PREFIX
              value: /opt/airflow/dags/repo/airflow/spark/
            - name: METASTORE_URI
              value: thrift://hive-metastore-svc.dataplatform.svc.cluster.local:9083
            - name: SPARK_IMAGE
              value: open-dataplatform-spark:3.1.2
          args: ["scheduler"]
          volumeMounts:
            - name: config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg
            - name: pod-template
              mountPath: /opt/airflow/pod-template.yml
              subPath: pod-template.yml
            - name: dags
              mountPath: /opt/airflow/dags
            - name: airflow-logs
              mountPath: "/opt/airflow/logs"
        - name: sync
          image: k8s.gcr.io/git-sync/git-sync:v3.3.4
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          env:
            - name: GIT_SYNC_ROOT
              value: /git
            - name: GIT_SYNC_DEST
              value: repo
            - name: GIT_SYNC_REPO
              value: https://github.com/jasondavindev/open-dataplatform.git
            - name: GIT_SYNC_BRANCH
              value: aiflow-fixes
            - name: GIT_SYNC_REV
              value: HEAD
            - name: GIT_SYNC_DEPTH
              value: "0"
            - name: GIT_SYNC_WAIT
              value: "20"
            - name: GIT_SYNC_TIMEOUT
              value: "120"
            - name: GIT_SYNC_ADD_USER
              value: "true"
            - name: GIT_SYNC_MAX_FAILURES
              value: "0"
            - name: GIT_KNOWN_HOSTS
              value: "false"
          volumeMounts:
            - name: dags
              mountPath: /git
      volumes:
        - name: config
          configMap:
            name: airflow-config
        - name: pod-template
          configMap:
            name: airflow-pod-template
        - name: dags
          emptyDir: {}
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs
