apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: airflow
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      serviceAccountName: airflow
      containers:
        - name: webserver
          image: open-dataplatform-airflow:v1.0
          env:
            - name: POSTGRES_HOST
              value: airflow-postgres-svc.airflow.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: EXECUTOR
              value: KubernetesExecutor
          ports:
            - containerPort: 8080
              name: web
          args: ["webserver", "-p", "8080"]
          volumeMounts:
            - name: config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg
            - name: dags
              mountPath: /opt/airflow/dags
        - name: sync
          image: k8s.gcr.io/git-sync/git-sync:v3.3.4
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          env:
            - name: GIT_SYNC_ROOT
              value: /git
            - name: GIT_SYNC_DEST
              value: repo
            - name: GIT_SYNC_REPO
              value: https://github.com/jasondavindev/open-dataplatform.git
            - name: GIT_SYNC_BRANCH
              value: main
            - name: GIT_SYNC_REV
              value: HEAD
            - name: GIT_SYNC_DEPTH
              value: "0"
            - name: GIT_SYNC_WAIT
              value: "60"
            - name: GIT_SYNC_TIMEOUT
              value: "120"
            - name: GIT_SYNC_ADD_USER
              value: "true"
            - name: GIT_SYNC_MAX_FAILURES
              value: "0"
            - name: GIT_KNOWN_HOSTS
              value: "false"
          volumeMounts:
            - name: dags
              mountPath: /git
      volumes:
        - name: config
          configMap:
            name: airflow-config
        - name: dags
          emptyDir: {}
