dk_prefix = docker exec namenode hdfs dfs

ls:
	${dk_prefix} -ls ${dir}

mkdir:
	${dk_prefix} -mkdir ${dir}

rm:
	${dk_prefix} -rm ${dir}

cat:
	${dk_prefix} -cat ${dir}

chown:
	${dk_prefix} -chown ${user} ${dir}
