create_admin:
	@docker exec airflow bash -c "airflow users create \
          --username admin \
          --firstname FIRST_NAME \
          --lastname LAST_NAME \
          --role Admin \
		  --password admin \
          --email admin@example.org"
