kind: ConfigMap
apiVersion: v1
metadata:
  name: hive-catalog-trino
  namespace: dataplatform
data:
  hive.properties: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://hive-metastore-svc.dataplatform.svc.cluster.local:9083
