kind: ConfigMap
apiVersion: v1
metadata:
  name: trino-jvm
  namespace: dataplatform
data:
  jvm.config: |
    -Duser.timezone=UTC
    -Xmx6G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Dcom.sun.management.jmxremote.rmi.port=9102
    -Dcom.sun.management.jmxremote.authenticate=false
    -Djdk.attach.allowAttachSelf=true
