apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: dataplatform
  labels:
    component: spark-master
spec:
  selector:
    matchLabels:
      component: spark-master
  replicas: 1
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      serviceAccountName: spark
      containers:
        - name: spark-master
          imagePullPolicy: IfNotPresent
          image: open-dataplatform-spark:3.1.2
          ports:
            - containerPort: 7077
              name: master
            - containerPort: 4040
              name: webui
          command:
            - sleep
            - "1000000000000000000"
          env:
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "4041"
            - name: SPARK_MASTER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: hive-site
              mountPath: /opt/hadoop/conf/hive-site.xml
              subPath: hive-site.xml
            - name: spark-defaults
              mountPath: /opt/spark/conf/spark-defaults.conf
              subPath: spark-defaults.conf
      volumes:
        - name: hive-site
          configMap:
            name: hive-site
        - name: spark-defaults
          configMap:
            name: spark-defaults
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
  namespace: dataplatform
spec:
  selector:
    component: spark-master
  type: ClusterIP
  ports:
    - name: master
      protocol: TCP
      port: 7077
    - name: webui
      protocol: TCP
      port: 4040
