apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: dataplatform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: dataplatform
  name: spark-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "edit", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: dataplatform
  name: spark-role-binding
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: dataplatform
roleRef:
  kind: ClusterRole
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
