apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickstream
  namespace: dataplatform
  labels:
    app: clickstream
spec:
  selector:
    matchLabels:
      app: clickstream
  replicas: 1
  template:
    metadata:
      labels:
        app: clickstream
    spec:
      serviceAccountName: spark
      containers:
        - name: clickstream
          imagePullPolicy: IfNotPresent
          image: open-dataplatform-spark:3.1.2
          command:
            - /opt/spark/bin/spark-submit
          args:
            - --master
            - k8s://https://$CONTROL_PLANE_IP:6443
            - --deploy-mode
            - cluster
            - --conf
            - "spark.executor.instances=1"
            - --conf
            - "spark.kubernetes.container.image=open-dataplatform-spark:3.1.2"
            - --conf
            - "spark.kubernetes.authenticate.driver.serviceAccountName=spark"
            - --conf
            - "spark.kubernetes.namespace=dataplatform"
            - --conf
            - "spark.hadoop.hive.metastore.uris=thrift://hive-metastore-svc.dataplatform.svc.cluster.local:9083"
            - --conf
            - "spark.kubernetes.authenticate.driver.serviceAccountName=spark"
            - --conf
            - "spark.kubernetes.driverEnv.APP_TOPIC=test"
            - --conf
            - "spark.kubernetes.driverEnv.KAFKA_BROKER=broker-svc.kafka.svc.cluster.local:29092"
            - hdfs://namenode-svc.dataplatform.svc.cluster.local/spark/scripts/v2.py
