apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickstream
  namespace: dataplatform
  labels:
    app: clickstream
spec:
  selector:
    matchLabels:
      app: clickstream
  replicas: 1
  template:
    metadata:
      labels:
        app: clickstream
    spec:
      serviceAccountName: spark
      containers:
        - name: clickstream
          imagePullPolicy: IfNotPresent
          image: open-dataplatform-spark:3.1.2
          command:
            - sleep
            - '10000000000000000000'
          command:
            - /bin/bash
            - '-c'
          args:
            - 'spark-submit --master k8s://https://172.21.0.3:6443 --conf "spark.eventLog.enabled=true" --conf "spark.eventLog.dir=hdfs://namenode-svc.dataplatform.svc.cluster.local:8020/tmp/spark-logs" --conf "spark.sql.warehouse.dir=hdfs://namenode-svc.dataplatform.svc.cluster.local:8020/user/hive/warehouse" --deploy-mode cluster --name clickstream --conf "spark.executor.instances=1" --conf "spark.kubernetes.container.image=open-dataplatform-spark:3.1.2" --conf "spark.kubernetes.authenticate.driver.serviceAccountName=spark" --conf "spark.kubernetes.namespace=dataplatform" --conf "spark.hadoop.hive.metastore.uris=thrift://hive-metastore-svc.dataplatform.svc.cluster.local:9083" hdfs://namenode-svc.dataplatform.svc.cluster.local:8020/spark/scripts/app.py --topic appclickstream --table-path hdfs://namenode-svc.dataplatform.svc.cluster.local:8020/spark/clickstream'
          volumeMounts:
            - name: application
              mountPath: /app.py
              subPath: app.py
      volumes:
        - name: application
          configMap:
            name: application-clickstream
