kind: ConfigMap
apiVersion: v1
metadata:
  name: entrypoint-datanode
  namespace: dataplatform
data:
  entrypoint.sh: |
    #!/bin/bash
    sed "s/NAMENODE_SVC_SERVICE_HOST/$NAMENODE_SVC_SERVICE_HOST/g" /tmp/core-site.xml > /etc/hadoop/core-site.xml
    sed "s/NAMENODE_SVC_SERVICE_HOST/$NAMENODE_SVC_SERVICE_HOST/g" \
        /tmp/hdfs-site.xml > /etc/hadoop/hdfs-site.xml
    $HADOOP_HOME/bin/hdfs --loglevel INFO,WARN,ERROR,Console --config $HADOOP_CONF_DIR datanode
